// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package protov1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuyProduct struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantities           int64    `protobuf:"varint,2,opt,name=quantities,proto3" json:"quantities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyProduct) Reset()         { *m = BuyProduct{} }
func (m *BuyProduct) String() string { return proto.CompactTextString(m) }
func (*BuyProduct) ProtoMessage()    {}
func (*BuyProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *BuyProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyProduct.Unmarshal(m, b)
}
func (m *BuyProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyProduct.Marshal(b, m, deterministic)
}
func (m *BuyProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyProduct.Merge(m, src)
}
func (m *BuyProduct) XXX_Size() int {
	return xxx_messageInfo_BuyProduct.Size(m)
}
func (m *BuyProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyProduct.DiscardUnknown(m)
}

var xxx_messageInfo_BuyProduct proto.InternalMessageInfo

func (m *BuyProduct) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *BuyProduct) GetQuantities() int64 {
	if m != nil {
		return m.Quantities
	}
	return 0
}

type Product struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Quantities           int64    `protobuf:"varint,3,opt,name=quantities,proto3" json:"quantities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetQuantities() int64 {
	if m != nil {
		return m.Quantities
	}
	return 0
}

type BuyProductsRequest struct {
	Products             []*BuyProduct `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BuyProductsRequest) Reset()         { *m = BuyProductsRequest{} }
func (m *BuyProductsRequest) String() string { return proto.CompactTextString(m) }
func (*BuyProductsRequest) ProtoMessage()    {}
func (*BuyProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *BuyProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyProductsRequest.Unmarshal(m, b)
}
func (m *BuyProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyProductsRequest.Marshal(b, m, deterministic)
}
func (m *BuyProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyProductsRequest.Merge(m, src)
}
func (m *BuyProductsRequest) XXX_Size() int {
	return xxx_messageInfo_BuyProductsRequest.Size(m)
}
func (m *BuyProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuyProductsRequest proto.InternalMessageInfo

func (m *BuyProductsRequest) GetProducts() []*BuyProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

type BuyProductsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyProductsResponse) Reset()         { *m = BuyProductsResponse{} }
func (m *BuyProductsResponse) String() string { return proto.CompactTextString(m) }
func (*BuyProductsResponse) ProtoMessage()    {}
func (*BuyProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *BuyProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyProductsResponse.Unmarshal(m, b)
}
func (m *BuyProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyProductsResponse.Marshal(b, m, deterministic)
}
func (m *BuyProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyProductsResponse.Merge(m, src)
}
func (m *BuyProductsResponse) XXX_Size() int {
	return xxx_messageInfo_BuyProductsResponse.Size(m)
}
func (m *BuyProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuyProductsResponse proto.InternalMessageInfo

type GetProductsRequest struct {
	ProductIds           []int64  `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsRequest) Reset()         { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()    {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *GetProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsRequest.Unmarshal(m, b)
}
func (m *GetProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsRequest.Marshal(b, m, deterministic)
}
func (m *GetProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsRequest.Merge(m, src)
}
func (m *GetProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsRequest.Size(m)
}
func (m *GetProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsRequest proto.InternalMessageInfo

func (m *GetProductsRequest) GetProductIds() []int64 {
	if m != nil {
		return m.ProductIds
	}
	return nil
}

type GetProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductsResponse) Reset()         { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()    {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}

func (m *GetProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsResponse.Unmarshal(m, b)
}
func (m *GetProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsResponse.Marshal(b, m, deterministic)
}
func (m *GetProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsResponse.Merge(m, src)
}
func (m *GetProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsResponse.Size(m)
}
func (m *GetProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsResponse proto.InternalMessageInfo

func (m *GetProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterType((*BuyProduct)(nil), "protov1.BuyProduct")
	proto.RegisterType((*Product)(nil), "protov1.Product")
	proto.RegisterType((*BuyProductsRequest)(nil), "protov1.BuyProductsRequest")
	proto.RegisterType((*BuyProductsResponse)(nil), "protov1.BuyProductsResponse")
	proto.RegisterType((*GetProductsRequest)(nil), "protov1.GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "protov1.GetProductsResponse")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xdd, 0x4a, 0xc3, 0x30,
	0x18, 0x86, 0x69, 0x8b, 0xce, 0xbd, 0xc5, 0x1f, 0xbe, 0x2a, 0x14, 0x7f, 0x47, 0x8e, 0x76, 0x20,
	0x15, 0x27, 0xde, 0x80, 0x22, 0x4e, 0x3c, 0x50, 0xe2, 0x05, 0x88, 0xae, 0x39, 0x08, 0xc8, 0xda,
	0x35, 0xe9, 0xc0, 0x0b, 0xf2, 0x3e, 0x85, 0x26, 0x4b, 0xb3, 0x65, 0x47, 0xa5, 0x79, 0xbf, 0xef,
	0xc9, 0x93, 0x17, 0xfb, 0x75, 0x53, 0x95, 0xed, 0x4c, 0x17, 0x75, 0x53, 0xe9, 0x8a, 0x06, 0xdd,
	0x67, 0x79, 0xcb, 0x5e, 0x81, 0x87, 0xf6, 0xf7, 0xdd, 0x84, 0x74, 0x01, 0xd8, 0xb9, 0x4f, 0x59,
	0xe6, 0xd1, 0x28, 0x1a, 0x27, 0x7c, 0x68, 0x4f, 0x5e, 0x4a, 0xba, 0x04, 0x16, 0xed, 0xd7, 0x5c,
	0x4b, 0x2d, 0x85, 0xca, 0xe3, 0x2e, 0xf6, 0x4e, 0xd8, 0x1b, 0x06, 0x2b, 0xd2, 0x01, 0x62, 0x47,
	0x88, 0x65, 0x49, 0xc7, 0xd8, 0xd1, 0x52, 0xff, 0x88, 0x6e, 0x6b, 0xc8, 0xcd, 0xcf, 0x06, 0x30,
	0x09, 0x80, 0x4f, 0xa0, 0xde, 0x4e, 0x71, 0xb1, 0x68, 0x85, 0xd2, 0x74, 0x83, 0x3d, 0xeb, 0xa4,
	0xf2, 0x68, 0x94, 0x8c, 0xd3, 0x49, 0x56, 0xd8, 0xf7, 0x14, 0xfd, 0x38, 0x77, 0x43, 0xec, 0x04,
	0xd9, 0x1a, 0x46, 0xd5, 0xd5, 0x5c, 0x09, 0x76, 0x0f, 0x7a, 0x16, 0x7a, 0x93, 0x7e, 0x85, 0xb4,
	0xef, 0xc0, 0x5c, 0x90, 0x70, 0xb8, 0x12, 0x14, 0x7b, 0x44, 0xb6, 0xb6, 0x66, 0x68, 0x74, 0x1d,
	0x58, 0x1d, 0x39, 0xab, 0x40, 0x69, 0xf2, 0x17, 0xe1, 0x70, 0x85, 0xf8, 0x10, 0xcd, 0x52, 0xce,
	0x04, 0x4d, 0x91, 0x7a, 0x60, 0x3a, 0x73, 0xeb, 0xa1, 0xe5, 0xe9, 0xf9, 0xf6, 0xd0, 0xba, 0x4c,
	0x91, 0x7a, 0x0f, 0xf6, 0x48, 0x61, 0x9b, 0x1e, 0x69, 0x4b, 0x47, 0xdf, 0xbb, 0x5d, 0x78, 0xf7,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0x71, 0x50, 0x5a, 0x97, 0x40, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductsServiceClient is the client API for ProductsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductsServiceClient interface {
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
	BuyProducts(ctx context.Context, in *BuyProductsRequest, opts ...grpc.CallOption) (*BuyProductsResponse, error)
}

type productsServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductsServiceClient(cc *grpc.ClientConn) ProductsServiceClient {
	return &productsServiceClient{cc}
}

func (c *productsServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, "/protov1.ProductsService/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) BuyProducts(ctx context.Context, in *BuyProductsRequest, opts ...grpc.CallOption) (*BuyProductsResponse, error) {
	out := new(BuyProductsResponse)
	err := c.cc.Invoke(ctx, "/protov1.ProductsService/BuyProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServiceServer is the server API for ProductsService service.
type ProductsServiceServer interface {
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	BuyProducts(context.Context, *BuyProductsRequest) (*BuyProductsResponse, error)
}

// UnimplementedProductsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductsServiceServer struct {
}

func (*UnimplementedProductsServiceServer) GetProducts(ctx context.Context, req *GetProductsRequest) (*GetProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (*UnimplementedProductsServiceServer) BuyProducts(ctx context.Context, req *BuyProductsRequest) (*BuyProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyProducts not implemented")
}

func RegisterProductsServiceServer(s *grpc.Server, srv ProductsServiceServer) {
	s.RegisterService(&_ProductsService_serviceDesc, srv)
}

func _ProductsService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protov1.ProductsService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_BuyProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).BuyProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protov1.ProductsService/BuyProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).BuyProducts(ctx, req.(*BuyProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protov1.ProductsService",
	HandlerType: (*ProductsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _ProductsService_GetProducts_Handler,
		},
		{
			MethodName: "BuyProducts",
			Handler:    _ProductsService_BuyProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
